title: Home
author: Johnny 2026
description: Physics and Mathematics Student at Dalhousie University. Interested in applied physics and mathematics (meteorology), computing, Vim.
avatar: "./assets/images/me.png"
hometitle: All posts
url: "" # Leave empty for now

social_links:
  - platform: github
    user_url: "https://github.com/johnnynaynay"
  - platform: twitter
    user_url: "https://x.com/johnnynaynay"
  - platform: instagram
    user_url: "https://instagram.com/johnnynaynay"

plugins:
  - jekyll-feed
  - jekyll-toc

toc:
  no_toc_section_class: "no_toc" # Add this class to any heading you want to hide
