title: Johnny's Blog
email: johnnynaynay@gmail.com
description: >- 
  
baseurl: "" 
url: "https://johnnynaynay.github.io" 

# Socials
twitter_username: johnnynaynay
github_username: johnnynaynay
instagram_username: johnnynaynay
discord_invite: "https://discord.gg/your-link-here" # Changed from username to invite link

# Sidebar Features
song_of_day:
  title: "Salad Days"
  artist: "Mac Demarco"
  cover: "/images/album-cover.jpg"
  spotify_url: "https://open.spotify.com/track/5VdaMUzoQetwxQwtWAd022?si=6aa87a105f594591"

equation_of_day:
  name: "Be Greater Than Average"
  latex: >-
    $$ B > \frac{1}{n} \sum_{i=1}^{n} x_i $$
  description: "A reminder to strive for excellence."

# Build settings
theme: minima
plugins:
  - jekyll-feed
